# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/project/xilinx/CPU10 - f/CPU.srcs/sources_1/ip/DM/DM.xci
# IP: The module: 'DM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/xilinx/CPU10 - f/CPU.gen/sources_1/ip/DM/DM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/project/xilinx/CPU10 - f/CPU.srcs/sources_1/ip/DM/DM.xci
# IP: The module: 'DM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/xilinx/CPU10 - f/CPU.gen/sources_1/ip/DM/DM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
